apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
