apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-exporter
  template:
    metadata:
      labels:
        app: haproxy-exporter
    spec:
      containers:
      - name: haproxy-exporter
        image: prom/haproxy-exporter:v0.12.0
        args:
          - '--haproxy.scrape-uri=http://username:password@haproxy-stats-service:8404/stats;csv'
        ports:
        - name: metrics
          containerPort: 9101
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9101
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9101
          initialDelaySeconds: 30
          timeoutSeconds: 10
